#!/bin/sh

curl --cookie cookie.txt \
			--cookie-jar cookie.txt \
			-s \
			-X 'POST' \
			'0.0.0.0:5000/v1/users/' \
			-H 'accept: application/json' \
			-H 'Content-Type: application/json' \
			-d @default_data/create_user.json
