#!/bin/sh

curl --cookie cookie.txt \
			--cookie-jar cookie.txt \
			-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (K HTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" \
			-s \
			-X 'POST' \
			'0.0.0.0:5000/v1/auth/login' \
			-H 'accept: application/json' \
			-H 'Content-Type: application/json' \
			-d @default_data/login.json
