#!/bin/sh

curl --cookie cookie.txt \
			--cookie-jar cookie.txt \
			-s \
			-X 'POST' \
			'0.0.0.0:5000/v1/auth/logout' \
			-H 'accept: application/json' \
			-H 'Content-Type: application/json' \
			-d '{}'
